# Generated by Django 4.2.2 on 2025-05-13 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0004_remove_profile_postal_code_remove_profile_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='identity_image',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='identity_type',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='state',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='twitter',
        ),
    ]
