# Generated by Django 4.2.2 on 2025-05-24 19:10

from django.db import migrations, models
import userauths.models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0006_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='default_profile_photo.png', null=True, upload_to=userauths.models.user_directory_path),
        ),
    ]
