# Generated by Django 4.2.2 on 2025-05-24 19:18

from django.db import migrations, models
import userauths.models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0007_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='default_profile_photo.jpg', null=True, upload_to=userauths.models.user_directory_path),
        ),
    ]
