# Generated by Django 4.2.2 on 2025-05-30 22:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0009_alter_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_type', models.CharField(choices=[('terms_of_use', 'Terms of Use'), ('privacy_policy', 'Privacy Policy'), ('personal_data', 'Personal Data Processing'), ('marketing', 'Marketing Communications'), ('booking_terms', 'Booking Terms'), ('payment_terms', 'Payment Terms')], max_length=50)),
                ('given_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('document_version', models.CharField(default='1.0', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-given_at'],
                'unique_together': {('user', 'consent_type', 'document_version')},
            },
        ),
    ]
