# Generated by Django 4.2.2 on 2025-06-14 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0011_alter_profile_options_alter_userconsent_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userconsent',
            name='ip_address',
        ),
    ]
