# Generated by Django 4.2.2 on 2025-06-23 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0013_add_database_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconsent',
            name='consent_type',
            field=models.CharField(choices=[('terms_of_use', 'Условия использования'), ('privacy_policy', 'Политика конфиденциальности'), ('personal_data', 'Обработка персональных данных'), ('marketing', 'Маркетинговые коммуникации'), ('booking_terms', 'Условия бронирования'), ('payment_terms', 'Условия оплаты'), ('hotel_owner_agreement', 'Соглашение с владельцами отелей')], max_length=50, verbose_name='Тип согласия'),
        ),
    ]
