[33mcommit 5ed546bd9dfc45f8423637e897c3962b60227ca9[m[33m ([m[1;36mHEAD[m[33m -> [m[1;32mdev[m[33m)[m
Author: Nurzhan Zhumataev <12farit21@gmail.com>
Date:   Mon Apr 28 01:31:41 2025 +0500

    adding new models and included this data into hotel_detail.html

[1mdiff --git a/db.sqlite3 b/db.sqlite3[m
[1mindex d7b13ee..df383d5 100644[m
Binary files a/db.sqlite3 and b/db.sqlite3 differ
[1mdiff --git a/hms_prj/settings.py b/hms_prj/settings.py[m
[1mindex 9828b6b..00642d6 100644[m
[1m--- a/hms_prj/settings.py[m
[1m+++ b/hms_prj/settings.py[m
[36m@@ -231,7 +231,7 @@[m [mJAZZMIN_SETTINGS = {[m
     'site_header': "Alakol",[m
     'site_brand': "Your #1 marketplace for collectibles.",[m
     'site_logo': "/images/logo.png",[m
[31m-    'copyright':  "All Right Reserved 2023",[m
[32m+[m[32m    'copyright':  "All Right Reserved 2024",[m
     "welcome_sign": "Welcome to Alakol HMS, Login Now.",[m
     "topmenu_links": [[m
 [m
[1mdiff --git a/hotel/admin.py b/hotel/admin.py[m
[1mindex 8aa66b3..b27cc1d 100644[m
[1m--- a/hotel/admin.py[m
[1m+++ b/hotel/admin.py[m
[36m@@ -1,6 +1,6 @@[m
 from django import forms[m
 from django.contrib import admin[m
[31m-from hotel.models import  ICON_CHOICES,Hotel, Room, Booking, RoomServices, HotelGallery, RoomTypeGallery,RoomTypeFeatures, HotelFeatures, HotelFAQs, RoomType, RoomTypeDescription,ActivityLog, StaffOnDuty, Coupon, CouponUsers, Notification, Bookmark, Review[m
[32m+[m[32mfrom hotel.models import  ICON_CHOICES,Hotel, Room, Booking, RoomServices, HotelGallery, RoomTypeGallery,RoomTypeFeatures, HotelFeatures, HotelFAQs, RoomType, RoomTypeDescription,ActivityLog, StaffOnDuty, Coupon, CouponUsers, Notification, Bookmark, Review, RoomTypeFeaturesDetailed[m
 from import_export.admin import ImportExportModelAdmin[m
 from django.utils.html import mark_safe[m
 [m
[36m@@ -46,6 +46,15 @@[m [mclass RoomTypeFeaturesForm(forms.ModelForm):[m
             'icon': IconSelectWidget(choices=ICON_CHOICES)  # Используем кастомный виджет для поля icon[m
         }[m
 [m
[32m+[m[32mclass RoomTypeFeaturesDetailedForm(forms.ModelForm):[m
[32m+[m[32m    text_ru = forms.CharField(max_length=100)[m
[32m+[m[32m    text_kk = forms.CharField(max_length=100)[m
[32m+[m[32m    text_en = forms.CharField(max_length=100)[m
[32m+[m[41m    [m
[32m+[m[32m    class Meta:[m
[32m+[m[32m        model = RoomTypeFeaturesDetailed[m
[32m+[m[32m        fields = '__all__'[m
[32m+[m
 class RoomTypeForm(forms.ModelForm):[m
     class Meta:[m
         model = RoomType[m
[36m@@ -206,11 +215,34 @@[m [mclass RoomTypeFeatures_Tab(admin.TabularInline):[m
 [m
         return formset[m
 [m
[32m+[m[32mclass RoomTypeFeaturesDetailed_Tab(admin.TabularInline):[m
[32m+[m[32m    model = RoomTypeFeaturesDetailed[m
[32m+[m[32m    form = RoomTypeFeaturesDetailedForm[m
[32m+[m[32m    extra = 0[m
[32m+[m[32m    exclude = ['text'][m
[32m+[m
[32m+[m[32m    def formfield_for_foreignkey(self, db_field, request, **kwargs):[m
[32m+[m[32m        if db_field.name == "room_type":[m
[32m+[m[32m            parent_id = request.resolver_match.kwargs.get('object_id')  # Получаем ID текущего отеля[m
[32m+[m[32m            if parent_id:[m
[32m+[m[32m                kwargs["queryset"] = RoomType.objects.filter(hotel_id=parent_id)[m
[32m+[m[32m        return super().formfield_for_foreignkey(db_field, request, **kwargs)[m
[32m+[m[41m    [m
[32m+[m[32m    def get_formset(self, request, obj=None, **kwargs):[m
[32m+[m[32m        formset = super().get_formset(request, obj, **kwargs)[m
[32m+[m
[32m+[m[32m        if request.user.groups.filter(name='Manager').exists() and not request.user.is_superuser:[m
[32m+[m[32m            for form in formset.form.base_fields.values():[m
[32m+[m[32m                if 'hfid' in formset.form.base_fields:[m
[32m+[m[32m                    formset.form.base_fields['hfid'].widget = forms.HiddenInput()[m
[32m+[m
[32m+[m[32m        return formset[m
[32m+[m
 class HotelAdmin(ImportExportModelAdmin):[m
     form = HotelAdminForm[m
     inlines = [[m
         HotelGallery_Tab, HotelFeatures_Tab, RoomType_Tab, RoomTypeDescription_Tab, [m
[31m-        RoomTypeGallery_Tab, RoomTypeFeatures_Tab, Room_Tab, HotelFAQs_Tab[m
[32m+[m[32m        RoomTypeGallery_Tab, RoomTypeFeatures_Tab, RoomTypeFeaturesDetailed_Tab, Room_Tab, HotelFAQs_Tab[m
     ][m
     search_fields = ['user__username', 'name'][m
     list_filter = ['featured', 'status'][m
[1mdiff --git a/hotel/migrations/0065_roomtypefeaturesdetailed.py b/hotel/migrations/0065_roomtypefeaturesdetailed.py[m
[1mnew file mode 100644[m
[1mindex 0000000..607d1fd[m
[1m--- /dev/null[m
[1m+++ b/hotel/migrations/0065_roomtypefeaturesdetailed.py[m
[36m@@ -0,0 +1,28 @@[m
[32m+[m[32m# Generated by Django 4.2.2 on 2025-04-27 19:10[m
[32m+[m
[32m+[m[32mfrom django.db import migrations, models[m
[32m+[m[32mimport django.db.models.deletion[m
[32m+[m
[32m+[m
[32m+[m[32mclass Migration(migrations.Migration):[m
[32m+[m
[32m+[m[32m    dependencies = [[m
[32m+[m[32m        ('hotel', '0064_alter_room_rid_alter_roomtypefeatures_hfid'),[m
[32m+[m[32m    ][m
[32m+[m
[32m+[m[32m    operations = [[m
[32m+[m[32m        migrations.CreateModel([m
[32m+[m[32m            name='RoomTypeFeaturesDetailed',[m
[32m+[m[32m            fields=[[m
[32m+[m[32m                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),[m
[32m+[m[32m                ('type_of_amenity', models.CharField(choices=[('private_bathroom', 'In the private bathroom'), ('view', 'View'), ('services_amenities', 'Services and amenities')], max_length=100, null=True)),[m
[32m+[m[32m                ('text', models.CharField(max_length=100)),[m
[32m+[m[32m                ('hfid', models.CharField(blank=True, max_length=20)),[m
[32m+[m[32m                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel')),[m
[32m+[m[32m                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roomtype_features_detailed', to='hotel.roomtype')),[m
[32m+[m[32m            ],[m
[32m+[m[32m            options={[m
[32m+[m[32m                'verbose_name_plural': 'Room Type Features Detailed',[m
[32m+[m[32m            },[m
[32m+[m[32m        ),[m
[32m+[m[32m    ][m
[1mdiff --git a/hotel/migrations/0066_roomtypefeaturesdetailed_text_en_and_more.py b/hotel/migrations/0066_roomtypefeaturesdetailed_text_en_and_more.py[m
[1mnew file mode 100644[m
[1mindex 0000000..82eff14[m
[1m--- /dev/null[m
[1m+++ b/hotel/migrations/0066_roomtypefeaturesdetailed_text_en_and_more.py[m
[36m@@ -0,0 +1,28 @@[m
[32m+[m[32m# Generated by Django 4.2.2 on 2025-04-27 20:20[m
[32m+[m
[32m+[m[32mfrom django.db import migrations, models[m
[32m+[m
[32m+[m
[32m+[m[32mclass Migration(migrations.Migration):[m
[32m+[m
[32m+[m[32m    dependencies = [[m
[32m+[m[32m        ('hotel', '0065_roomtypefeaturesdetailed'),[m
[32m+[m[32m    ][m
[32m+[m
[32m+[m[32m    operations = [[m
[32m+[m[32m        migrations.AddField([m
[32m+[m[32m            model_name='roomtypefeaturesdetailed',[m
[32m+[m[32m            name='text_en',[m
[32m+[m[32m            field=models.CharField(max_length=100, null=True),[m
[32m+[m[32m        ),[m
[32m+[m[32m        migrations.AddField([m
[32m+[m[32m            model_name='roomtypefeaturesdetailed',[m
[32m+[m[32m            name='text_kk',[m
[32m+[m[32m            field=models.CharField(max_length=100, null=True),[m
[32m+[m[32m        ),[m
[32m+[m[32m        migrations.AddField([m
[32m+[m[32m            model_name='roomtypefeaturesdetailed',[m
[32m+[m[32m            name='text_ru',[m
[32m+[m[32m            field=models.CharField(max_length=100, null=True),[m
[32m+[m[32m        ),[m
[32m+[m[32m    ][m
[1mdiff --git a/hotel/models.py b/hotel/models.py[m
[1mindex 74e9829..0ad4de6 100644[m
[1m--- a/hotel/models.py[m
[1m+++ b/hotel/models.py[m
[36m@@ -90,6 +90,13 @@[m [mRATING = ([m
     ( 5,  "★★★★★"),[m
 )[m
 [m
[32m+[m[32mROOM_TYPE_FEATURES_DETAILED = [[m
[32m+[m[32m    ('private_bathroom', 'In the private bathroom'),[m
[32m+[m[32m    ('view', 'View'),[m
[32m+[m[32m    ('services_amenities', 'Services and amenities'),[m
[32m+[m[32m][m
[32m+[m
[32m+[m
 class Hotel(models.Model):[m
     user = models.ForeignKey(User, on_delete=models.CASCADE)[m
     name = models.CharField(max_length=100,blank=True)[m
[36m@@ -290,6 +297,30 @@[m [mclass RoomTypeFeatures(models.Model):[m
     class Meta:[m
         verbose_name_plural = "Room Type Features"[m
 [m
[32m+[m[32mclass RoomTypeFeaturesDetailed(models.Model):[m
[32m+[m[32m    hotel = models.ForeignKey(Hotel, on_delete=models.CASCADE)[m
[32m+[m[32m    room_type = models.ForeignKey(RoomType, on_delete=models.CASCADE, related_name='roomtype_features_detailed')[m
[32m+[m[32m    type_of_amenity = models.CharField(max_length=100, null=True, choices=ROOM_TYPE_FEATURES_DETAILED)[m
[32m+[m[32m    text = models.CharField(max_length=100)[m
[32m+[m[32m    hfid = models.CharField(max_length=20,blank=True)[m
[32m+[m
[32m+[m[32m    def save(self, *args, **kwargs):[m
[32m+[m[32m        # Генерация уникального hfid, если оно отсутствует[m
[32m+[m[32m        if not self.hfid:[m
[32m+[m[32m            self.hfid = shortuuid.uuid()[:10][m
[32m+[m
[32m+[m[32m        while RoomTypeFeaturesDetailed.objects.filter(hfid=self.hfid).exists():[m
[32m+[m[32m            self.hfid = shortuuid.uuid()[:10]  # Regenerate if it already exists[m
[32m+[m[41m    [m
[32m+[m[32m        super().save(*args, **kwargs)[m
[32m+[m
[32m+[m
[32m+[m[32m    def __str__(self):[m
[32m+[m[32m        return str(self.hotel)[m
[32m+[m[41m    [m
[32m+[m[32m    class Meta:[m
[32m+[m[32m        verbose_name_plural = "Room Type Features Detailed"[m
[32m+[m
 class Room(models.Model):[m
     hotel = models.ForeignKey(Hotel, on_delete=models.CASCADE)[m
     room_type = models.ForeignKey(RoomType, on_delete=models.CASCADE)[m
[1mdiff --git a/hotel/translation.py b/hotel/translation.py[m
[1mindex 4977adb..e9479b2 100644[m
[1m--- a/hotel/translation.py[m
[1m+++ b/hotel/translation.py[m
[36m@@ -1,5 +1,5 @@[m
 from modeltranslation.translator import register, TranslationOptions[m
[31m-from .models import Hotel, HotelFAQs, RoomTypeDescription[m
[32m+[m[32mfrom .models import Hotel, HotelFAQs, RoomTypeDescription, RoomTypeFeaturesDetailed[m
 [m
 @register(Hotel)[m
 class HotelTranslationOptions(TranslationOptions):[m
[36m@@ -11,4 +11,8 @@[m [mclass HotelFAQsTranslationOptions(TranslationOptions):[m
 [m
 @register(RoomTypeDescription)[m
 class RoomTypeDescriptionTranslationOptions(TranslationOptions):[m
[31m-    fields = ['description'][m
\ No newline at end of file[m
[32m+[m[32m    fields = ['description'][m
[32m+[m
[32m+[m[32m@register(RoomTypeFeaturesDetailed)[m
[32m+[m[32mclass RoomTypeFeaturesDetailedTranslationOptions(TranslationOptions):[m
[32m+[m[32m    fields = ('text',)  # Указываем поле для перевода[m
\ No newline at end of file[m
[1mdiff --git a/locale/ru/LC_MESSAGES/django.po b/locale/ru/LC_MESSAGES/django.po[m
[1mindex 655e646..fdeeeda 100644[m
[1m--- a/locale/ru/LC_MESSAGES/django.po[m
[1m+++ b/locale/ru/LC_MESSAGES/django.po[m
[36m@@ -540,7 +540,7 @@[m [mmsgstr "Исследуйте самые замечательные места н[m
 [m
 #: .\templates\hotel\index.html:54 .\templates\hotel\index_translated.html:54[m
 msgid "Open Now"[m
[31m-msgstr "Открой сейчас"[m
[32m+[m[32mmsgstr "Открыто сейчас"[m
 [m
 #: .\templates\hotel\index.html:68 .\templates\hotel\index_translated.html:68[m
 msgid "No Rating Yet"[m
[1mdiff --git a/templates/hotel/hotel_detail.html b/templates/hotel/hotel_detail.html[m
[1mindex 500c895..5a4fea1 100644[m
[1m--- a/templates/hotel/hotel_detail.html[m
[1m+++ b/templates/hotel/hotel_detail.html[m
[36m@@ -246,6 +246,69 @@[m
         margin: 0 0 12px;[m
     }[m
 [m
[32m+[m[32m    /* Стили для особенностей номера */[m
[32m+[m[32m    .room-features-section {[m
[32m+[m[32m        margin-top: 20px;[m
[32m+[m[32m    }[m
[32m+[m
[32m+[m[32m    .room-feature-category {[m
[32m+[m[32m        font-weight: bold;[m
[32m+[m[32m        color: #2c3e50;[m
[32m+[m[32m        margin: 15px 0 10px;[m
[32m+[m[32m        {% comment %} font-size: 1.1em; {% endcomment %}[m
[32m+[m[32m    }[m
[32m+[m
[32m+[m[32m    .room-feature-list {[m
[32m+[m[32m        list-style: none;[m
[32m+[m[32m        padding: 0;[m
[32m+[m[32m        margin: 0;[m
[32m+[m[32m    }[m
[32m+[m
[32m+[m[32m    .room-feature-item {[m
[32m+[m[32m        display: flex;[m
[32m+[m[32m        align-items: center;[m
[32m+[m[32m        margin-bottom: 8px;[m
[32m+[m[32m        padding: 5px 0;[m
[32m+[m[32m    }[m
[32m+[m
[32m+[m[32m    .room-feature-item i {[m
[32m+[m[32m        color: #27ae60;[m
[32m+[m[32m        margin-right: 10px;[m
[32m+[m[32m        font-size: 1.1em;[m
[32m+[m[32m    }[m
[32m+[m
[32m+[m[32m    /* Стили для иконок характеристик */[m
[32m+[m[32m    .room-features-icons {[m
[32m+[m[32m        display: flex;[m
[32m+[m[32m        flex-wrap: wrap;[m
[32m+[m[32m        gap: 15px;[m
[32m+[m[32m        margin: 15px 0;[m
[32m+[m[32m        padding: 10px;[m
[32m+[m[32m        background: #f8f9fa;[m
[32m+[m[32m        border-radius: 8px;[m
[32m+[m[32m    }[m
[32m+[m
[32m+[m[32m    .feature-icon-item {[m
[32m+[m[32m        display: flex;[m
[32m+[m[32m        align-items: center;[m
[32m+[m[32m        gap: 8px;[m
[32m+[m[32m    }[m
[32m+[m
[32m+[m[32m    .feature-icon-item img {[m
[32m+[m[32m        width: 24px;[m
[32m+[m[32m        height: 24px;[m
[32m+[m[32m        object-fit: contain;[m
[32m+[m[32m    }[m
[32m+[m
[32m+[m[32m    /* Стили для размера комнаты */[m
[32m+[m[32m    .room-size-info {[m
[32m+[m[32m        margin: 15px 0;[m
[32m+[m[32m        padding: 10px;[m
[32m+[m[32m        background: #f8f9fa;[m
[32m+[m[32m        border-radius: 8px;[m
[32m+[m[32m        font-weight: 500;[m
[32m+[m[32m    }[m
[32m+[m
     .custom-modal-footer {[m
         padding: 12px;[m
         background: #ecf0f1;[m
[36m@@ -672,6 +735,31 @@[m
                 {% empty %}[m
                 <p>{% trans "No description available." %}</p>[m
                 {% endfor %}[m
[32m+[m
[32m+[m[32m                <div class="room-size-info">[m
[32m+[m[32m                    {% trans "Room size" %}: {{ r.room_size }} m²[m
[32m+[m[32m                </div>[m
[32m+[m
[32m+[m[32m                <div class="room-features-icons">[m
[32m+[m[32m                    {% for feature in r.roomtype_features.all %}[m
[32m+[m[32m                    <div class="feature-icon-item">[m
[32m+[m[32m                        <img src="{% static 'icons/' %}{{ feature.icon }}" alt="{{ feature.name }}">[m
[32m+[m[32m                        <span>{{ feature.name }}</span>[m
[32m+[m[32m                    </div>[m
[32m+[m[32m                    {% endfor %}[m
[32m+[m[32m                </div>[m
[32m+[m
[32m+[m[32m                <div class="room-features-section">[m
[32m+[m[32m                    {% for feature in r.roomtype_features_detailed.all %}[m
[32m+[m[32m                        {% ifchanged feature.type_of_amenity %}[m
[32m+[m[32m                            <div class="room-feature-category">{{ feature.type_of_amenity }}:</div>[m
[32m+[m[32m                        {% endifchanged %}[m
[32m+[m[32m                        <div class="room-feature-item">[m
[32m+[m[32m                            <i class="fas fa-check"></i>[m
[32m+[m[32m                            <span>{{ feature.text }}</span>[m
[32m+[m[32m                        </div>[m
[32m+[m[32m                    {% endfor %}[m
[32m+[m[32m                </div>[m
             </div>[m
         </div>[m
         <div class="custom-modal-footer">[m
[1mdiff --git a/templates/hotel/index.html b/templates/hotel/index.html[m
[1mindex c0de36f..dfa5790 100644[m
[1m--- a/templates/hotel/index.html[m
[1m+++ b/templates/hotel/index.html[m
[36m@@ -73,7 +73,7 @@[m
                                                 <div class="utf_counter_star_rating">{{h.average_rating}}/5 ({{h.rating_count}} {% trans "reviews" %}) </div>[m
                                                 {% endif %}[m
                                                     [m
[31m-                                                <span class="utf_view_count"> {{h.views}}</span>[m
[32m+[m[32m                                                {% comment %} <span class="utf_view_count"> {{h.views}}</span> {% endcomment %}[m
                                                 <span class="like-icon add-to-bookmark-{{h.id}}" data-hotel="{{h.id}}" id="add-to-bookmark"></span>[m
                                             </div>[m
                                         </a>[m
