# Generated by Django 4.2.2 on 2025-08-17 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='on_homepage',
            field=models.BooleanField(default=False, help_text='Отображать новость на главной странице', verbose_name='На главной'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['on_homepage', 'published_at'], name='news_news_on_home_3058c4_idx'),
        ),
    ]
