# Generated by Django 4.2.2 on 2025-05-30 22:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('terms_of_use', 'Terms of Use'), ('privacy_policy', 'Privacy Policy'), ('public_offer', 'Public Offer'), ('booking_rules', 'Booking Rules'), ('personal_data_consent', 'Personal Data Consent'), ('payment_rules', 'Payment Rules')], max_length=50)),
                ('version', models.CharField(max_length=10)),
                ('content', models.TextField()),
                ('effective_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
                ('language', models.CharField(default='en', max_length=2)),
            ],
            options={
                'unique_together': {('document_type', 'version', 'language')},
            },
        ),
        migrations.CreateModel(
            name='DocumentView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=50)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-viewed_at'],
            },
        ),
    ]
