# Generated by Django 4.2.2 on 2025-06-14 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentview',
            name='ip_address',
        ),
    ]
