# Generated by Django 4.2.2 on 2025-05-11 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotel', '0075_booking_created_at_booking_expires_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomUnavailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.room')),
            ],
            options={
                'verbose_name': 'Недоступность номера',
                'verbose_name_plural': 'Недоступность номеров',
                'indexes': [models.Index(fields=['room', 'start_date', 'end_date'], name='booking_roo_room_id_e6f68f_idx')],
            },
        ),
    ]
