# Generated by Django 4.2.2 on 2025-06-04 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0090_alter_hotel_options_alter_booking_before_discount_and_more'),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomunavailability',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='roomunavailability',
            name='end_date',
            field=models.DateField(verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='roomunavailability',
            name='reason',
            field=models.CharField(blank=True, max_length=255, verbose_name='Причина'),
        ),
        migrations.AlterField(
            model_name='roomunavailability',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.room', verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='roomunavailability',
            name='start_date',
            field=models.DateField(verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='roomunavailability',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
    ]
