"""
Django settings for hms_prj project.

Generated by 'django-admin startproject' using Django 3.2.18.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os
import secrets

from django.utils.translation import gettext

from dotenv import load_dotenv
 

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Use environment variable or generate a secure key
SECRET_KEY = os.getenv('SECRET_KEY', secrets.token_urlsafe(50))

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'jazzmin',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',  # Добавлено для SEO

    # Custom Apps
    'hotel',
    'booking',
    'addon',
    'userauths',
    'user_dashboard',
    'search',
    'robokassa',
    'legal',
    'news.apps.NewsConfig',

    # Third Party Apps
    'import_export',
    'crispy_forms',
    'mathfilters',
    'taggit',
    "anymail",
    'geoip2',
    'django_user_agents',
    'storages',
    'channels',
    'multiupload',
    'modeltranslation',
    'django.contrib.humanize',
    'django_crontab',
    'clearcache',

    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'hotel.middleware.AdminRussianLanguageMiddleware',  # Принудительно устанавливает русский для админки
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'legal.middleware.AdminLegalConsentMiddleware',  # Проверка согласия с legal agreements для админки
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]

ROOT_URLCONF = 'hms_prj.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.i18n',
                'hotel.context_processor.default',
                'hotel.context_processor.admin_russian_language',  # Принудительно русский для админки
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'legal.context_processors.legal_documents',
                'news.context_processors.news_context',  # Контекст для новостей
            ],
        },
    },
]

WSGI_APPLICATION = 'hms_prj.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT'),
    }
}

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'Asia/Yekaterinburg'  # UTC+5, Алматы не обновленый там +6 до сих пор

USE_I18N = True

USE_L10N = True

USE_THOUSAND_SEPARATOR = False

USE_TZ = True

gettext = lambda s:s
LANGUAGES = (
    ("kk", gettext("Kazakh")),
    ("ru", gettext("Russia")),
    ("en", gettext("English")),

)

LOCALE_PATHS = (
    os.path.join(BASE_DIR, 'locale'),
)

# Настройки для языкового cookie
LANGUAGE_COOKIE_NAME = 'django_language'
LANGUAGE_COOKIE_AGE = None  # Действует до закрытия браузера
LANGUAGE_COOKIE_DOMAIN = None
LANGUAGE_COOKIE_PATH = '/'
LANGUAGE_COOKIE_SECURE = False
LANGUAGE_COOKIE_HTTPONLY = False
LANGUAGE_COOKIE_SAMESITE = None

# ==============================================
# MODELTRANSLATION SETTINGS
# ==============================================

# Настройки для django-modeltranslation
MODELTRANSLATION_DEFAULT_LANGUAGE = 'ru'  # По умолчанию русский
MODELTRANSLATION_FALLBACK_LANGUAGES = ('kk', 'ru', 'en')  # Порядок резервных языков
MODELTRANSLATION_LANGUAGES = ('kk', 'ru', 'en')  # Поддерживаемые языки для переводов

# Настройки валидации переводов
MODELTRANSLATION_ENABLE_FALLBACKS = True  # Разрешить использование резервных языков
MODELTRANSLATION_PREPOPULATE_LANGUAGE = 'ru'  # Автозаполнение форм на русском

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

MEDIA_URL = '/media/'

MEDIA_ROOT = os.path.join(BASE_DIR, "media")

LOGIN_URL = "userauths:sign-in"

LOGIN_REDIRECT_URL = ""

LOGOUT_REDIRECT_URL = "userauths:sign-in"

AUTH_USER_MODEL = 'userauths.User'

AUTHENTICATION_BACKENDS = [
    'userauths.backends.CaseInsensitiveEmailBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# Website Address
WEBSITE_ADDRESS = os.getenv("WEBSITE_ADDRESS")

# Anymail
EMAIL_BACKEND = os.getenv("EMAIL_BACKEND")

DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL")
ANYMAIL = {
    "MAILGUN_API_KEY": os.getenv("MAILGUN_API_KEY"),
    "MAILGUN_SENDER_DOMAIN": os.getenv("MAILGUN_SENDER_DOMAIN"),  
}

# AWS SES Configuration
AWS_ACCESS_KEY_ID = os.getenv("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = os.getenv("AWS_SECRET_ACCESS_KEY")
AWS_REGION = os.getenv("AWS_REGION", "ap-south-1")
AWS_SES_REGION_NAME = AWS_REGION
AWS_SES_REGION_ENDPOINT = f'email.{AWS_REGION}.amazonaws.com'


# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'





JAZZMIN_SETTINGS = {
    'site_header': "Alakol",
    'site_brand': ".",
    'site_logo': "/images/logo.png",
    'copyright':  "Все права защищены 2025",
    "welcome_sign": "Добро пожаловать в Alakol HMS, войдите сейчас.",
    
    "language_chooser": False,
    
    "topmenu_links": [
        #{"name": "Главная",  "url": "admin:index", "permissions": ["auth.view_user"]},
        # {"name": "Company", "url": "/admin/addons/company/"},
        # {"name": "Users", "url": "/admin/userauths/user/"},

        {"model": "AUTH_USER_MODEL.User"},
    ],

    "order_with_respect_to": [
        "hotel",
        "booking",
        "news",
        "hotel.Hotel",
        "hotel.RoomTypeComplete",
        "hotel.Room",
        "hotel.RoomType",
        "hotel.RoomServices",
        "hotel.Bookmark",
        "hotel.Coupon",
        "hotel.Review",
        "hotel.Notification",
        "news.NewsCategory",
        "news.News",
        "news.NewsGallery",
        "userauths",
        "addons",
    ],
    
    "icons": {
        "admin.LogEntry": "fas fa-file",

        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",

        "userauths.User": "fas fa-user",
        "userauths.Profile":"fas fa-address-card",

        "hotel.Hotel": "fas fa-th",
        "hotel.RoomTypeComplete": "fas fa-cogs",
        "hotel.Room":"fas fa-bed",
        "hotel.RoomType":"fas fa-dollar-sign",
        "hotel.Booking":"fas fa-calendar-week",
        "hotel.RoomServices":"fas fa-user-cog",
        "hotel.Bookmark":"fas fa-heart",
        "hotel.Coupon":"fas fa-tag",
        "hotel.Review":"fas fa-star",
        "hotel.Notification":"fas fa-bell",
        
        "news.NewsCategory": "fas fa-folder",
        "news.News": "fas fa-newspaper",
        "news.NewsGallery": "fas fa-images",
    },

    "custom_css": "admin/css/custom_admin.css",
    "show_ui_builder" : True
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": True,
    "brand_small_text": False,
    "brand_colour": "navbar-indigo",
    "accent": "accent-olive",
    "navbar": "navbar-indigo navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": False,
    "sidebar": "sidebar-dark-indigo",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "default",
    "dark_mode_theme": "default",
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}



# Robokassa Settings
ROBOKASSA_MERCHANT_LOGIN = os.getenv('ROBOKASSA_MERCHANT_LOGIN')
ROBOKASSA_MERCHANT_PASSWORD_1 = os.getenv('ROBOKASSA_MERCHANT_PASSWORD_1')
ROBOKASSA_MERCHANT_PASSWORD_2 = os.getenv('ROBOKASSA_MERCHANT_PASSWORD_2')
ROBOKASSA_TEST_PASSWORD_1 = os.getenv('ROBOKASSA_TEST_PASSWORD_1')
ROBOKASSA_TEST_PASSWORD_2 = os.getenv('ROBOKASSA_TEST_PASSWORD_2')
ROBOKASSA_USE_TEST_MODE = os.getenv('ROBOKASSA_USE_TEST_MODE') == 'True'



CSRF_TRUSTED_ORIGINS = [
    'https://*.ngrok-free.app',
    'http://localhost:8000',
    'https://b855-2a0d-b201-c0-774-907e-b5d8-ed29-207b.ngrok-free.app',
]

# Redis Configuration for Caching
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": os.getenv("REDIS_URL", "redis://127.0.0.1:6379/1"),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "CONNECTION_POOL_KWARGS": {
                "max_connections": 50,
                "health_check_interval": 30,
            },
            "COMPRESSOR": "django_redis.compressors.zlib.ZlibCompressor",
            "SERIALIZER": "django_redis.serializers.pickle.PickleSerializer",
        },
        "KEY_PREFIX": "hms_alakol",
        "TIMEOUT": 300,  # 5 минут по умолчанию 300
    },

    "long_term": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": os.getenv("REDIS_URL", "redis://127.0.0.1:6379/3"),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "CONNECTION_POOL_KWARGS": {
                "max_connections": 20,
                "health_check_interval": 60,
            },
            "COMPRESSOR": "django_redis.compressors.zlib.ZlibCompressor",
        },
        "KEY_PREFIX": "hms_longterm",
        "TIMEOUT": 3600,  # 1 час для долгосрочных данных 3600
    }
}

# Session Configuration - используем базу данных для сессий (без кэширования)
SESSION_ENGINE = "django.contrib.sessions.backends.db"
SESSION_COOKIE_AGE = 86400  # 24 часа
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_SAVE_EVERY_REQUEST = True


# Cache Middleware Configuration - ОТКЛЮЧЕНО для данных реального времени
# MIDDLEWARE.insert(1, 'django.middleware.cache.UpdateCacheMiddleware')
# MIDDLEWARE.append('django.middleware.cache.FetchFromCacheMiddleware')

# Cache времена жизни для различных типов данных
CACHE_TTL = {
    'hotels_list': 900,         # 15 минут - список отелей
    'hotel_detail': 1800,       # 30 минут - детали отеля
    'search_results': 300,      # 5 минут - результаты поиска
    #'room_availability': 0,    # ОТКЛЮЧЕНО - доступность номеров (без кеширования)
    'hotel_reviews': 3600,      # 1 час - отзывы отеля
    'features_and_amenities': 7200,  # 2 часа - удобства и особенности
    'static_content': 86400,    # 24 часа - статический контент
    # Настройки для booking приложения
    #'room_unavailability': 0,      # ОТКЛЮЧЕНО - недоступность номеров (без кеширования)
    
    # Настройки для dashboard статистики
    'dashboard_stats': 300,     # 5 минут - основная статистика дашборда
    
    # ОТКЛЮЧЕННЫЕ ТИПЫ КЭШИРОВАНИЯ для данных реального времени:
    # 'booking_data': 0,              # ОТКЛЮЧЕНО - данные бронирования должны обновляться мгновенно
    # 'user_bookings': 0,             # ОТКЛЮЧЕНО - бронирования пользователя должны обновляться мгновенно  
    # 'dynamic_pricing': 0,           # ОТКЛЮЧЕНО - динамические цены должны обновляться мгновенно
    # 'booking_availability_check': 0, # ОТКЛЮЧЕНО - проверка доступности должна быть в реальном времени
    # 'booking_session_data': 0,      # ОТКЛЮЧЕНО - данные сессии бронирования должны обновляться мгновенно
    # 'user_notifications': 0,        # ОТКЛЮЧЕНО - уведомления пользователей должны отображаться мгновенно
    # 'user_profile_data': 0,         # ОТКЛЮЧЕНО - профильные данные пользователя могут изменяться часто
    # 'live_inventory': 0,            # ОТКЛЮЧЕНО - текущие остатки номеров должны быть точными
    # 'payment_status': 0,            # ОТКЛЮЧЕНО - статусы платежей должны обновляться немедленно
    # 'cart_data': 0,                 # ОТКЛЮЧЕНО - корзина пользователя должна отражать актуальное состояние
}

CRONJOBS = [
    ('*/5 * * * *', 'hotel.cron.handle_bookings_payment_status_processing'),
]

# Настройки логирования
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': 'debug.log',
            'formatter': 'verbose',
            'encoding': 'utf-8',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'hotel.views': {
            'handlers': ['file', 'console'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'robokassa.robokassa': {
            'handlers': ['file', 'console'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}


