# Generated by Django 4.2.2 on 2025-05-01 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RobokassaPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(max_length=100, unique=True, verbose_name='Номер счета')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('success', 'Успешно'), ('fail', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус')),
                ('payment_data', models.TextField(blank=True, help_text='Дополнительная информация о платеже', verbose_name='Данные платежа')),
            ],
            options={
                'verbose_name': 'Платеж Робокассы',
                'verbose_name_plural': 'Платежи Робокассы',
            },
        ),
    ]
