# Generated by Django 4.2.4 on 2023-09-07 16:47

from django.db import migrations, models
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0022_booking_before_discount_booking_saved'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='stripe_payment_intent',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='success_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvxyz1234567890', blank=True, length=300, max_length=505, null=True),
        ),
    ]