# Generated by Django 4.2.2 on 2024-09-13 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0030_booking_checked_in_tracker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='room_gallery'),
        ),
    ]
