# Generated by Django 4.2.2 on 2024-09-13 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0031_roomtype_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='room_gallery'),
        ),
    ]
