# Generated by Django 4.2.2 on 2024-09-13 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0032_room_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomtype',
            name='image',
        ),
    ]
