# Generated by Django 4.2.2 on 2024-09-14 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0038_roomtypegallery_delete_roomtypeimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomtypegallery',
            options={'verbose_name_plural': 'Room Type Gallery'},
        ),
        migrations.RemoveField(
            model_name='room',
            name='image',
        ),
    ]
