# Generated by Django 4.2.2 on 2024-09-14 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0039_alter_roomtypegallery_options_remove_room_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtypegallery',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roomtype_gallery', to='hotel.roomtype'),
        ),
    ]
