# Generated by Django 4.2.2 on 2024-09-23 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0041_hotel_address_en_hotel_address_kz_hotel_address_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='address_en',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='address_kz',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='address_ru',
        ),
    ]
