# Generated by Django 4.2.2 on 2024-09-23 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0042_remove_hotel_address_en_remove_hotel_address_kz_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='description_kz',
            new_name='description_kk',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='name_kz',
            new_name='name_kk',
        ),
        migrations.RenameField(
            model_name='hotelfaqs',
            old_name='answer_kz',
            new_name='answer_kk',
        ),
        migrations.RenameField(
            model_name='hotelfaqs',
            old_name='question_kz',
            new_name='question_kk',
        ),
    ]
