# Generated by Django 4.2.2 on 2024-09-24 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0045_rename_description_roomtype_room_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='room_description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='room_description_kk',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='room_description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='type_en',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='type_kk',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='type_ru',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
