# Generated by Django 4.2.2 on 2024-09-24 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0046_roomtype_room_description_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomtype',
            name='type_en',
        ),
        migrations.RemoveField(
            model_name='roomtype',
            name='type_kk',
        ),
        migrations.RemoveField(
            model_name='roomtype',
            name='type_ru',
        ),
    ]
