# Generated by Django 4.2.2 on 2024-09-27 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0047_remove_roomtype_type_en_remove_roomtype_type_kk_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelfeatures',
            name='icon_type',
        ),
    ]
