# Generated by Django 4.2.2 on 2024-09-27 20:13

from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0048_remove_hotelfeatures_icon_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomTypeFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(max_length=100)),
                ('hfid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvxyz', length=10, max_length=20, prefix='', unique=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roomtype_features', to='hotel.roomtype')),
            ],
            options={
                'verbose_name_plural': 'Room Type Features',
            },
        ),
    ]
