# Generated by Django 4.2.2 on 2024-09-27 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0049_roomtypefeatures'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='room_size',
            field=models.IntegerField(default=0),
        ),
    ]
