# Generated by Django 4.2.2 on 2024-09-27 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0050_roomtype_room_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='room_size',
            field=models.IntegerField(default=0, verbose_name='Room size (m²)'),
        ),
    ]
