# Generated by Django 4.2.2 on 2024-09-27 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0051_alter_roomtype_room_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomtype',
            name='room_description',
        ),
        migrations.RemoveField(
            model_name='roomtype',
            name='room_description_en',
        ),
        migrations.RemoveField(
            model_name='roomtype',
            name='room_description_kk',
        ),
        migrations.RemoveField(
            model_name='roomtype',
            name='room_description_ru',
        ),
    ]
