# Generated by Django 4.2.2 on 2024-09-27 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0052_remove_roomtype_room_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomTypeDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roomtype_description', to='hotel.roomtype')),
            ],
            options={
                'verbose_name_plural': 'Room Type Description',
            },
        ),
    ]
