# Generated by Django 4.2.2 on 2024-09-27 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0053_roomtypedescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtypedescription',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roomtypedescription',
            name='description_kk',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roomtypedescription',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
    ]
