# Generated by Django 4.2.2 on 2024-10-28 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0054_roomtypedescription_description_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='name_kk',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='name_ru',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
