# Generated by Django 4.2.2 on 2024-12-02 05:48

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0056_alter_hotelgallery_hgid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelgallery',
            name='hgid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvxyz0123456789', length=10, max_length=20, prefix='', unique=True),
        ),
    ]
