# Generated by Django 4.2.2 on 2024-12-02 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0059_alter_roomtype_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelfaqs',
            name='hfid',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='hotelfeatures',
            name='hfid',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='hotelgallery',
            name='hgid',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='rtid',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
