# Generated by Django 4.2.2 on 2024-12-02 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0062_alter_hotelfaqs_hfid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='rtid',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
