# Generated by Django 4.2.2 on 2025-04-27 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0064_alter_room_rid_alter_roomtypefeatures_hfid'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomTypeFeaturesDetailed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_amenity', models.CharField(choices=[('private_bathroom', 'In the private bathroom'), ('view', 'View'), ('services_amenities', 'Services and amenities')], max_length=100, null=True)),
                ('text', models.CharField(max_length=100)),
                ('hfid', models.CharField(blank=True, max_length=20)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roomtype_features_detailed', to='hotel.roomtype')),
            ],
            options={
                'verbose_name_plural': 'Room Type Features Detailed',
            },
        ),
    ]
