# Generated by Django 4.2.2 on 2025-04-27 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0065_roomtypefeaturesdetailed'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtypefeaturesdetailed',
            name='text_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='roomtypefeaturesdetailed',
            name='text_kk',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='roomtypefeaturesdetailed',
            name='text_ru',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
