# Generated by Django 4.2.2 on 2025-04-29 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0066_roomtypefeaturesdetailed_text_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='check_in_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='check_out_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
