# Generated by Django 4.2.2 on 2025-05-01 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0067_hotel_check_in_time_hotel_check_out_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='stripe_payment_intent',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='success_id',
        ),
    ]
