# Generated by Django 4.2.2 on 2025-05-04 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0068_remove_payment_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='inv_id',
            field=models.CharField(blank=True, help_text='ID платежа в Робокассе', max_length=100, null=True),
        ),
    ]
