# Generated by Django 4.2.2 on 2025-05-04 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0069_booking_inv_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='inv_id',
        ),
        migrations.AddField(
            model_name='booking',
            name='robokassa_inv_id',
            field=models.IntegerField(blank=True, help_text='InvId from Robokassa payment system', null=True),
        ),
    ]
