# Generated by Django 4.2.2 on 2025-05-04 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0071_alter_booking_robokassa_inv_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='robokassa_inv_id',
            field=models.IntegerField(blank=True, help_text='InvId from Robokassa payment system', null=True),
        ),
    ]
