# Generated by Django 4.2.2 on 2025-05-04 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0072_alter_booking_robokassa_inv_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booked_rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.booking')),
                ('room', models.ManyToManyField(to='hotel.room')),
            ],
            options={
                'verbose_name': 'Забронированный номер',
                'verbose_name_plural': 'Забронированные номера',
            },
        ),
    ]
