# Generated by Django 4.2.2 on 2025-05-04 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0073_booked_rooms'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booked_rooms',
        ),
    ]
