# Generated by Django 4.2.2 on 2025-05-06 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0074_delete_booked_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['expires_at'], name='hotel_booki_expires_17ff4c_idx'),
        ),
    ]
