# Generated by Django 4.2.2 on 2025-05-12 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0076_room_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='creator',
        ),
    ]
