# Generated by Django 4.2.2 on 2025-05-12 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0077_remove_room_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='country_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
