# Generated by Django 4.2.2 on 2025-05-13 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0078_booking_country_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffonduty',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='tags',
        ),
        migrations.DeleteModel(
            name='ActivityLog',
        ),
        migrations.DeleteModel(
            name='StaffOnDuty',
        ),
    ]
