# Generated by Django 4.2.2 on 2025-05-13 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0079_remove_staffonduty_booking_remove_hotel_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='dynamic_pricing',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
