# Generated by Django 4.2.2 on 2025-05-13 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0080_roomtype_dynamic_pricing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='dynamic_pricing',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
