# Generated by Django 4.2.2 on 2025-05-16 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0081_alter_roomtype_dynamic_pricing'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceOnDate',
            fields=[
            ],
            options={
                'verbose_name': 'Цена по датам',
                'verbose_name_plural': 'Цены по датам',
                'permissions': [('view_price_manager', 'Can view price as manager'), ('change_price_manager', 'Can change price as manager')],
                'proxy': True,
                'default_permissions': ('add', 'change', 'delete', 'view'),
                'indexes': [],
                'constraints': [],
            },
            bases=('hotel.roomtype',),
        ),
        migrations.AlterModelOptions(
            name='roomtype',
            options={'verbose_name': 'Тип комнаты', 'verbose_name_plural': 'Типы комнат'},
        ),
    ]
