# Generated by Django 4.2.2 on 2025-05-16 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0082_priceondate_alter_roomtype_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PriceOnDate',
        ),
    ]
