# Generated by Django 4.2.2 on 2025-05-16 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0083_delete_priceondate'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='roomtypedescription',
            constraint=models.UniqueConstraint(fields=('room_type',), name='unique_room_type_description'),
        ),
    ]
