# Generated by Django 4.2.2 on 2025-05-16 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0084_roomtypedescription_unique_room_type_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='type',
            field=models.CharField(max_length=120),
        ),
    ]
