# Generated by Django 4.2.2 on 2025-05-19 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0085_alter_roomtype_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='end_date',
            field=models.DateField(blank=True, help_text='Дата окончания работы отеля', null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='start_date',
            field=models.DateField(blank=True, help_text='Дата начала работы отеля', null=True),
        ),
    ]
