# Generated by Django 4.2.2 on 2025-05-24 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0086_hotel_end_date_hotel_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelfeatures',
            name='name',
            field=models.CharField(max_length=35),
        ),
    ]
