# Generated by Django 4.2.2 on 2025-05-28 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0087_alter_hotelfeatures_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='selection_data',
            field=models.JSONField(blank=True, help_text='Данные о выбранных номерах из selection_data_obj', null=True),
        ),
    ]
