# Generated by Django 4.2.2 on 2025-06-03 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0088_booking_selection_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotel',
            options={'verbose_name': 'Отель', 'verbose_name_plural': 'Отели'},
        ),
    ]
