# Generated by Django 4.2.2 on 2025-06-04 02:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotel', '0089_alter_hotel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotel',
            options={},
        ),
        migrations.AlterField(
            model_name='booking',
            name='before_discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='До скидки'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvxyz', length=10, max_length=20, prefix='', unique=True, verbose_name='ID бронирования'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_in_date',
            field=models.DateField(verbose_name='Дата заезда'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_out_date',
            field=models.DateField(verbose_name='Дата выезда'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='checked_in',
            field=models.BooleanField(default=False, verbose_name='Заселен'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='checked_in_tracker',
            field=models.BooleanField(default=False, help_text='DO NOT CHECK THIS BOX', verbose_name='Трекер заселения'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='checked_out',
            field=models.BooleanField(default=False, verbose_name='Выселен'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='checked_out_tracker',
            field=models.BooleanField(default=False, help_text='DO NOT CHECK THIS BOX', verbose_name='Трекер выселения'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='country_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Код страны'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='coupons',
            field=models.ManyToManyField(blank=True, to='hotel.coupon', verbose_name='Купоны'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Создано в'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Истекает в'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='full_name',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Полное имя'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel.hotel', verbose_name='Отель'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='num_adults',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество взрослых'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='num_children',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество детей'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Оплачено'), ('pending', 'Ожидает'), ('processing', 'Обрабатывается'), ('cancelled', 'Отменено'), ('initiated', 'Инициировано'), ('failed', 'Не удалось'), ('refunding', 'Возвращается'), ('refunded', 'Возвращено'), ('unpaid', 'Не оплачено'), ('expired', 'Истекло')], default='initiated', max_length=100, verbose_name='Статус оплаты'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='robokassa_inv_id',
            field=models.IntegerField(blank=True, help_text='InvId from Robokassa payment system', null=True, verbose_name='ID инвойса Robokassa'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.ManyToManyField(to='hotel.room', verbose_name='Номера'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel.roomtype', verbose_name='Тип номера'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='saved',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Сэкономлено'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='selection_data',
            field=models.JSONField(blank=True, help_text='Данные о выбранных номерах из selection_data_obj', null=True, verbose_name='Данные выбора'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Итого'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_days',
            field=models.PositiveIntegerField(default=0, verbose_name='Общее количество дней'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='bid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvxyz', length=10, max_length=20, prefix='', unique=True, verbose_name='ID закладки'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel', verbose_name='Отель'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='cid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvxyz', length=10, max_length=25, prefix='', verbose_name='ID купона'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(max_length=1000, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='make_public',
            field=models.BooleanField(default=False, verbose_name='Сделать публичным'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='redemption',
            field=models.IntegerField(default=0, verbose_name='Количество использований'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='type',
            field=models.CharField(choices=[('Percentage', 'Процент'), ('Flat Rate', 'Фиксированная сумма')], default='Percentage', max_length=100, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_from',
            field=models.DateField(verbose_name='Действителен с'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_to',
            field=models.DateField(verbose_name='Действителен до'),
        ),
        migrations.AlterField(
            model_name='couponusers',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.booking', verbose_name='Бронирование'),
        ),
        migrations.AlterField(
            model_name='couponusers',
            name='coupon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.coupon', verbose_name='Купон'),
        ),
        migrations.AlterField(
            model_name='couponusers',
            name='email',
            field=models.CharField(max_length=1000, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='couponusers',
            name='full_name',
            field=models.CharField(max_length=1000, verbose_name='Полное имя'),
        ),
        migrations.AlterField(
            model_name='couponusers',
            name='mobile',
            field=models.CharField(max_length=1000, verbose_name='Мобильный телефон'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='address',
            field=models.CharField(max_length=200, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='check_in_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время заезда'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='check_out_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время выезда'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='description_kk',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='email',
            field=models.CharField(max_length=20, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='end_date',
            field=models.DateField(blank=True, help_text='Дата окончания работы отеля', null=True, verbose_name='Дата окончания работы'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='Рекомендуемый'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvxyz', length=10, max_length=20, prefix='', unique=True, verbose_name='ID отеля'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='image',
            field=models.FileField(upload_to='hotel_gallery', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='mobile',
            field=models.CharField(max_length=20, verbose_name='Мобильный телефон'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='name_kk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='name_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='start_date',
            field=models.DateField(blank=True, help_text='Дата начала работы отеля', null=True, verbose_name='Дата начала работы'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='status',
            field=models.CharField(blank=True, choices=[('Draft', 'Черновик'), ('Disabled', 'Отключен'), ('Rejected', 'Отклонен'), ('In Review', 'На проверке'), ('Live', 'Опубликован')], default='published', max_length=10, null=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='Просмотры'),
        ),
        migrations.AlterField(
            model_name='hotelfaqs',
            name='answer',
            field=models.TextField(blank=True, null=True, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='hotelfaqs',
            name='answer_en',
            field=models.TextField(blank=True, null=True, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='hotelfaqs',
            name='answer_kk',
            field=models.TextField(blank=True, null=True, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='hotelfaqs',
            name='answer_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='hotelfaqs',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='hotelfaqs',
            name='hfid',
            field=models.CharField(blank=True, max_length=20, verbose_name='ID FAQ'),
        ),
        migrations.AlterField(
            model_name='hotelfaqs',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel', verbose_name='Отель'),
        ),
        migrations.AlterField(
            model_name='hotelfaqs',
            name='question',
            field=models.CharField(max_length=1000, verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='hotelfaqs',
            name='question_en',
            field=models.CharField(max_length=1000, null=True, verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='hotelfaqs',
            name='question_kk',
            field=models.CharField(max_length=1000, null=True, verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='hotelfaqs',
            name='question_ru',
            field=models.CharField(max_length=1000, null=True, verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='hotelfeatures',
            name='hfid',
            field=models.CharField(blank=True, max_length=20, verbose_name='ID особенности'),
        ),
        migrations.AlterField(
            model_name='hotelfeatures',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel', verbose_name='Отель'),
        ),
        migrations.AlterField(
            model_name='hotelfeatures',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='hotelfeatures',
            name='name',
            field=models.CharField(max_length=35, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='hotelgallery',
            name='hgid',
            field=models.CharField(blank=True, max_length=20, verbose_name='ID галереи'),
        ),
        migrations.AlterField(
            model_name='hotelgallery',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel', verbose_name='Отель'),
        ),
        migrations.AlterField(
            model_name='hotelgallery',
            name='image',
            field=models.FileField(upload_to='hotel_gallery', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.booking', verbose_name='Бронирование'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='nid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvxyz', length=10, max_length=20, prefix='', unique=True, verbose_name='ID уведомления'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='seen',
            field=models.BooleanField(default=False, verbose_name='Просмотрено'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('Booking Confirmed', 'Бронирование подтверждено'), ('Booking Cancelled', 'Бронирование отменено')], default='new_order', max_length=100, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='review',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='review',
            name='helpful',
            field=models.ManyToManyField(blank=True, related_name='helpful', to=settings.AUTH_USER_MODEL, verbose_name='Полезно'),
        ),
        migrations.AlterField(
            model_name='review',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='hotel.hotel', verbose_name='Отель'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, '★☆☆☆☆'), (2, '★★☆☆☆'), (3, '★★★☆☆'), (4, '★★★★☆'), (5, '★★★★★')], default=None, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='review',
            name='reply',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.TextField(blank=True, null=True, verbose_name='Отзыв'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='room',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='room',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel', verbose_name='Отель'),
        ),
        migrations.AlterField(
            model_name='room',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Доступен'),
        ),
        migrations.AlterField(
            model_name='room',
            name='rid',
            field=models.CharField(blank=True, max_length=20, verbose_name='ID номера'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.CharField(max_length=10, verbose_name='Номер комнаты'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.roomtype', verbose_name='Тип номера'),
        ),
        migrations.AlterField(
            model_name='roomservices',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.booking', verbose_name='Бронирование'),
        ),
        migrations.AlterField(
            model_name='roomservices',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='roomservices',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='roomservices',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.room', verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='roomservices',
            name='service_type',
            field=models.CharField(choices=[('Food', 'Питание'), ('Cleaning', 'Уборка'), ('Technical', 'Техническое обслуживание')], max_length=20, verbose_name='Тип услуги'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='dynamic_pricing',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Динамические цены'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel', verbose_name='Отель'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='number_of_beds',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество кроватей'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='room_capacity',
            field=models.PositiveIntegerField(default=0, verbose_name='Вместимость'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='room_size',
            field=models.IntegerField(default=0, verbose_name='Размер комнаты (м²)'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='rtid',
            field=models.CharField(blank=True, max_length=20, verbose_name='ID типа номера'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='type',
            field=models.CharField(max_length=120, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='roomtypedescription',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='roomtypedescription',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='roomtypedescription',
            name='description_kk',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='roomtypedescription',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='roomtypedescription',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel', verbose_name='Отель'),
        ),
        migrations.AlterField(
            model_name='roomtypedescription',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roomtype_description', to='hotel.roomtype', verbose_name='Тип номера'),
        ),
        migrations.AlterField(
            model_name='roomtypefeatures',
            name='hfid',
            field=models.CharField(blank=True, max_length=20, verbose_name='ID особенности'),
        ),
        migrations.AlterField(
            model_name='roomtypefeatures',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel', verbose_name='Отель'),
        ),
        migrations.AlterField(
            model_name='roomtypefeatures',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='roomtypefeatures',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='roomtypefeatures',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roomtype_features', to='hotel.roomtype', verbose_name='Тип номера'),
        ),
        migrations.AlterField(
            model_name='roomtypefeaturesdetailed',
            name='hfid',
            field=models.CharField(blank=True, max_length=20, verbose_name='ID особенности'),
        ),
        migrations.AlterField(
            model_name='roomtypefeaturesdetailed',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel', verbose_name='Отель'),
        ),
        migrations.AlterField(
            model_name='roomtypefeaturesdetailed',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roomtype_features_detailed', to='hotel.roomtype', verbose_name='Тип номера'),
        ),
        migrations.AlterField(
            model_name='roomtypefeaturesdetailed',
            name='text',
            field=models.CharField(max_length=100, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='roomtypefeaturesdetailed',
            name='text_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='roomtypefeaturesdetailed',
            name='text_kk',
            field=models.CharField(max_length=100, null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='roomtypefeaturesdetailed',
            name='text_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='roomtypefeaturesdetailed',
            name='type_of_amenity',
            field=models.CharField(choices=[('private_bathroom', 'В частной ванной'), ('view', 'Вид'), ('services_amenities', 'Услуги и удобства')], max_length=100, null=True, verbose_name='Тип удобства'),
        ),
        migrations.AlterField(
            model_name='roomtypegallery',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel', verbose_name='Отель'),
        ),
        migrations.AlterField(
            model_name='roomtypegallery',
            name='image',
            field=models.ImageField(upload_to='room_type_images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='roomtypegallery',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roomtype_gallery', to='hotel.roomtype', verbose_name='Тип номера'),
        ),
    ]
