# Generated by Django 4.2.2 on 2025-06-04 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0090_alter_hotel_options_alter_booking_before_discount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotelfaqs',
            options={'verbose_name_plural': 'Вопрос/Ответ'},
        ),
        migrations.AlterModelOptions(
            name='hotelfeatures',
            options={'verbose_name_plural': 'Удобства отеля'},
        ),
        migrations.AlterModelOptions(
            name='hotelgallery',
            options={'verbose_name_plural': 'Галерея отеля'},
        ),
        migrations.AlterModelOptions(
            name='roomtypedescription',
            options={'verbose_name_plural': 'Описание типа номера'},
        ),
        migrations.AlterModelOptions(
            name='roomtypefeatures',
            options={'verbose_name_plural': 'Удобства типа номера'},
        ),
        migrations.AlterModelOptions(
            name='roomtypefeaturesdetailed',
            options={'verbose_name_plural': 'Удобства типа номера подробно'},
        ),
        migrations.AlterModelOptions(
            name='roomtypegallery',
            options={'verbose_name_plural': 'Галерея типа номера'},
        ),
    ]
