# Generated by Django 4.2.2 on 2025-06-07 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0091_alter_hotelfaqs_options_alter_hotelfeatures_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_for_hotel',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='90% от общей суммы', max_digits=12, verbose_name='К оплате отелю (90%)'),
        ),
        migrations.AddField(
            model_name='booking',
            name='prepayment',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='10% от общей суммы', max_digits=12, verbose_name='Предоплата (10%)'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='num_adults',
            field=models.PositiveIntegerField(default=1, verbose_name='Взрослые'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='num_children',
            field=models.PositiveIntegerField(default=0, verbose_name='Дети'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_days',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во дней'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
