# Generated by Django 4.2.2 on 2025-06-08 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0092_booking_payment_for_hotel_booking_prepayment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='end_date',
            field=models.DateField(blank=True, help_text='Дата окончания работы отеля', null=True, verbose_name='Дата окончания работы отеля'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='start_date',
            field=models.DateField(blank=True, help_text='Дата начала работы отеля', null=True, verbose_name='Дата начала работы отеля'),
        ),
    ]
