# Generated by Django 4.2.2 on 2025-06-15 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0093_alter_hotel_end_date_alter_hotel_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='legal_agreements',
            field=models.JSONField(blank=True, help_text='Согласия с юридическими документами при оплате', null=True, verbose_name='Юридические согласия'),
        ),
    ]
