# Generated by Django 4.2.2 on 2025-06-15 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0094_booking_legal_agreements'),
    ]

    operations = [
    ]
