# Generated by Django 4.2.2 on 2025-06-21 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0100_add_database_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='meal_included_in_price',
            field=models.CharField(choices=[('yes', 'Да'), ('no', 'Нет')], default='no', max_length=3, verbose_name='Включено ли питание в стоимость?'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='meal_plan_type',
            field=models.CharField(choices=[('not_included', 'Не включено'), ('full_board', 'Трехразовое питание'), ('half_board_lunch_dinner', 'Двухразовое (обед + ужин)'), ('half_board_breakfast_lunch', 'Двухразовое (завтрак + обед)'), ('breakfast_only', 'Только завтрак'), ('lunch_only', 'Только обед'), ('dinner_only', 'Только ужин')], default='not_included', max_length=50, verbose_name='Тип комплексного питания'),
        ),
        migrations.CreateModel(
            name='HotelMealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(help_text='Например: Завтрак, Обед, Ужин', max_length=100, verbose_name='Тип питания')),
                ('price_per_day', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Цена за день')),
                ('age_min', models.PositiveIntegerField(default=0, verbose_name='Минимальный возраст')),
                ('age_max', models.PositiveIntegerField(default=99, verbose_name='Максимальный возраст')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('hmpid', models.CharField(blank=True, max_length=20, verbose_name='ID плана питания')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel', verbose_name='Отель')),
            ],
            options={
                'verbose_name': 'План питания отеля',
                'verbose_name_plural': 'Планы питания отеля',
                'ordering': ['price_per_day'],
            },
        ),
    ]
