# Generated by Django 4.2.2 on 2025-06-21 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0101_hotel_meal_included_in_price_hotel_meal_plan_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelmealplan',
            name='description',
        ),
        migrations.RemoveField(
            model_name='hotelmealplan',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='hotelmealplan',
            name='meal_type',
        ),
        migrations.AlterField(
            model_name='hotelmealplan',
            name='age_max',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Максимальный возраст'),
        ),
    ]
