# Generated by Django 4.2.2 on 2025-06-21 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0102_remove_meal_plan_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='meal_included_in_price',
            field=models.CharField(choices=[('yes', 'Да'), ('no', 'Нет')], default='no', max_length=3, verbose_name='Включено ли питание в стоимость номера?'),
        ),
    ]
