# Generated by Django 4.2.2 on 2025-07-04 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0103_alter_hotel_meal_included_in_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtypefeaturesdetailed',
            name='type_of_amenity',
            field=models.CharField(choices=[('private_bathroom', 'В частном санузле'), ('view', 'Вид'), ('services_amenities', 'Услуги и удобства')], max_length=100, null=True, verbose_name='Тип удобства'),
        ),
    ]
