# Generated by Django 4.2.2 on 2025-07-07 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0104_alter_roomtypefeaturesdetailed_type_of_amenity'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomTypeComplete',
            fields=[
            ],
            options={
                'verbose_name': 'Управление типом номера',
                'verbose_name_plural': 'Управление типами номеров',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('hotel.roomtype',),
        ),
        migrations.RemoveField(
            model_name='roomtypedescription',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='roomtypedescription',
            name='description_kk',
        ),
        migrations.RemoveField(
            model_name='roomtypedescription',
            name='description_ru',
        ),
        migrations.AddField(
            model_name='roomtype',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='description_kk',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
