# Generated by Django 4.2.2 on 2025-07-07 04:09

from django.db import migrations


def migrate_roomtype_descriptions(apps, schema_editor):
    """
    Переносит данные из RoomTypeDescription в RoomType
    """
    RoomType = apps.get_model('hotel', 'RoomType')
    RoomTypeDescription = apps.get_model('hotel', 'RoomTypeDescription')
    
    # Переносим данные из RoomTypeDescription в RoomType
    for description in RoomTypeDescription.objects.all():
        try:
            room_type = description.room_type
            if room_type:
                # Переносим основное описание
                if description.description:
                    room_type.description = description.description
                
                # Переносим локализованные описания если они есть
                if hasattr(description, 'description_ru') and description.description_ru:
                    room_type.description_ru = description.description_ru
                if hasattr(description, 'description_kk') and description.description_kk:
                    room_type.description_kk = description.description_kk
                if hasattr(description, 'description_en') and description.description_en:
                    room_type.description_en = description.description_en
                
                room_type.save()
                print(f"Migrated description for RoomType {room_type.id}: {room_type.type}")
        except Exception as e:
            print(f"Error migrating description for RoomType {description.room_type_id}: {e}")


def reverse_migrate_roomtype_descriptions(apps, schema_editor):
    """
    Обратная миграция - переносит данные обратно в RoomTypeDescription
    """
    RoomType = apps.get_model('hotel', 'RoomType')
    RoomTypeDescription = apps.get_model('hotel', 'RoomTypeDescription')
    
    # Создаем записи RoomTypeDescription для каждого RoomType который имеет description
    for room_type in RoomType.objects.all():
        if room_type.description or (hasattr(room_type, 'description_ru') and room_type.description_ru):
            # Проверяем, есть ли уже описание для этого типа номера
            existing_description = RoomTypeDescription.objects.filter(room_type=room_type).first()
            if not existing_description:
                description = RoomTypeDescription(
                    hotel=room_type.hotel,
                    room_type=room_type,
                    description=room_type.description or ''
                )
                
                # Переносим локализованные описания
                if hasattr(room_type, 'description_ru') and room_type.description_ru:
                    description.description_ru = room_type.description_ru
                if hasattr(room_type, 'description_kk') and room_type.description_kk:
                    description.description_kk = room_type.description_kk
                if hasattr(room_type, 'description_en') and room_type.description_en:
                    description.description_en = room_type.description_en
                
                description.save()
                print(f"Reverse migrated description for RoomType {room_type.id}: {room_type.type}")


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0105_add_description_to_roomtype'),
    ]

    operations = [
        migrations.RunPython(
            migrate_roomtype_descriptions,
            reverse_migrate_roomtype_descriptions,
        ),
    ]
