# Generated by Django 4.2.2 on 2025-07-07 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0106_migrate_roomtype_description_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoomTypeDescription',
        ),
    ]
