# Generated by Django 4.2.2 on 2025-07-08 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0107_remove_roomtype_description_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomtypecomplete',
            options={'verbose_name': 'Тип номера', 'verbose_name_plural': 'Типы номеров'},
        ),
    ]
