# Generated by Django 4.2.2 on 2025-07-09 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0108_alter_roomtypecomplete_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelfeatures',
            name='hfid',
            field=models.CharField(blank=True, max_length=20, verbose_name='ID удобства'),
        ),
        migrations.AlterField(
            model_name='roomtypefeatures',
            name='hfid',
            field=models.CharField(blank=True, max_length=20, verbose_name='ID удобства'),
        ),
        migrations.AlterField(
            model_name='roomtypefeaturesdetailed',
            name='hfid',
            field=models.CharField(blank=True, max_length=20, verbose_name='ID удобства'),
        ),
    ]
