# Generated by Django 4.2.2 on 2025-07-09 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0109_alter_hotelfeatures_hfid_alter_roomtypefeatures_hfid_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Номер', 'verbose_name_plural': 'Номера'},
        ),
        migrations.RemoveField(
            model_name='booking',
            name='room',
        ),
        migrations.AddField(
            model_name='booking',
            name='room',
            field=models.TextField(blank=True, help_text='Список номеров в текстовом формате', null=True, verbose_name='Номера'),
        ),
    ]
