# Generated by Django 4.2.2 on 2025-07-10 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0110_change_room_field_to_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.TextField(blank=True, null=True, verbose_name='Номера'),
        ),
    ]
