# Generated by Django 4.2.2 on 2025-07-11 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0111_alter_booking_room'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotelfaqs',
            options={'verbose_name': 'Вопрос/Ответ', 'verbose_name_plural': 'Вопрос/Ответ'},
        ),
    ]
