# Generated by Django 4.2.2 on 2025-07-12 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0112_alter_hotelfaqs_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotelfeatures',
            options={'verbose_name': 'Удобство отеля', 'verbose_name_plural': 'Удобства отеля'},
        ),
    ]
