# Generated by Django 4.2.2 on 2025-07-15 18:56

import django.core.validators
from django.db import migrations, models
import hotel.models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0113_alter_hotelfeatures_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='image',
            field=models.ImageField(upload_to='hotel_gallery', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif']), hotel.models.validate_image], verbose_name='Изображение'),
        ),
    ]
