# Generated by Django 4.2.2 on 2025-07-15 18:58

import django.core.validators
from django.db import migrations, models
import hotel.models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0114_alter_hotel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='image',
            field=models.ImageField(upload_to='hotel_gallery', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), hotel.models.validate_image], verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='hotelgallery',
            name='image',
            field=models.ImageField(upload_to='hotel_gallery', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), hotel.models.validate_image], verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='roomtypegallery',
            name='image',
            field=models.ImageField(upload_to='room_type_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), hotel.models.validate_image], verbose_name='Изображение'),
        ),
    ]
