# Generated by Django 4.2.2 on 2025-08-10 23:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0115_alter_hotel_image_alter_hotelgallery_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='min_days_for_booking',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Кол-во мин дней для бронирования'),
        ),
    ]
