# Generated by Django 4.2.2 on 2025-08-12 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0116_alter_hotel_end_date_alter_hotel_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='check_in_time',
            field=models.TimeField(null=True, verbose_name='Время заезда'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='check_out_time',
            field=models.TimeField(null=True, verbose_name='Время выезда'),
        ),
    ]
