# Generated by Django 4.2.2 on 2025-08-12 21:51

import django.core.validators
from django.db import migrations, models
import hotel.models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0117_alter_hotel_check_in_time_alter_hotel_check_out_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='end_date',
            field=models.CharField(help_text='Дата окончания сезона работы отеля (ДД.ММ)', max_length=5, null=True, validators=[django.core.validators.RegexValidator('^\\d{2}\\.\\d{2}$', message='Используйте формат ДД.ММ'), hotel.models.validate_ddmm], verbose_name='Дата окончания работы отеля'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='start_date',
            field=models.CharField(help_text='Дата начала сезона работы отеля (ДД.ММ)', max_length=5, null=True, validators=[django.core.validators.RegexValidator('^\\d{2}\\.\\d{2}$', message='Используйте формат ДД.ММ'), hotel.models.validate_ddmm], verbose_name='Дата начала работы отеля'),
        ),
    ]
