# Generated by Django 4.2.2 on 2025-08-13 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0116_hotel_min_days_for_booking'),
        ('hotel', '0118_alter_hotel_end_date_alter_hotel_start_date'),
    ]

    operations = [
    ]
