# Generated by Django 4.2.2 on 2025-08-13 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0119_merge_20250813_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelfeatures',
            name='name_en',
            field=models.CharField(max_length=35, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='hotelfeatures',
            name='name_kk',
            field=models.CharField(max_length=35, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='hotelfeatures',
            name='name_ru',
            field=models.CharField(max_length=35, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='type_en',
            field=models.CharField(max_length=120, null=True, verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='type_kk',
            field=models.CharField(max_length=120, null=True, verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='type_ru',
            field=models.CharField(max_length=120, null=True, verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='roomtypefeatures',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='roomtypefeatures',
            name='name_kk',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='roomtypefeatures',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Название'),
        ),
    ]
