# Generated by Django 4.2.2 on 2025-08-13 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0120_hotelfeatures_name_en_hotelfeatures_name_kk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='type',
            field=models.CharField(blank=True, max_length=120, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='type_en',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='type_kk',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='type_ru',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Тип'),
        ),
    ]
