# Generated by Django 5.2.17 on 2026-09-06 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0121_alter_roomtype_type_alter_roomtype_type_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelfeatures',
            name='name',
            field=models.CharField(blank=True, max_length=35, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='hotelfeatures',
            name='name_en',
            field=models.CharField(blank=True, max_length=35, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='hotelfeatures',
            name='name_kk',
            field=models.CharField(blank=True, max_length=35, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='hotelfeatures',
            name='name_ru',
            field=models.CharField(blank=True, max_length=35, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='roomtypefeatures',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='roomtypefeatures',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='roomtypefeatures',
            name='name_kk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='roomtypefeatures',
            name='name_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название'),
        ),
    ]
